blog/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views as pages_views
urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    path('kansa/', admin.site.urls),
    # Url of pages app start from
    path('', include('pages.urls', namespace='pages')),

]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),


]

pages/urls.py
from django.urls import path
from . import views

#Unique namespace for pages app
app_name='pages'

urlpatterns =[
    path("", views.home , name="home"),
    path("posts/<int:pk>/<slug:slug>/", views.post_detail , name="post_detail"),
    path("posts/create/", views.post_create , name="post_create"),
    path("posts/update/<int:pk>/<slug:slug>/", views.post_update , name="post_update"),
    path("posts/remove/<int:pk>/<slug:slug>/", views.post_remove , name="post_remove"),

    path('blogpost-like/<int:pk>/<slug:slug>/', views.BlogPostLike, name="post_like"),
    path('nested-comment/', views.nested_comment, name="nested_comment"),
    path('logout/', views.Logout,  name='logout'),
    path("accounts/register", views.register_request, name="register")






]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} #Boot strap css CDN {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block title %}
    <title>My Blog</title>  
    {% endblock title %}
    <style>
      ul.errorlist li{
        list-style: none;
        color: red;
      }
    </style>
   
</head>
  <body>
    {% comment %} #Navbar {% endcomment %}
    <div>
        {% include  'navbar.html' %}
    </div>
    {% comment %} #main content {% endcomment %}

    <main class="container my-4">
      {% if messages %}
      <ul class="list-group">
          {% for message in messages %}
          <li {% if message.tags %} class="list-group-item list-group-item-{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}


        <div class="row">
            {% block content %}

            <div class="col-lg-9">
            {% for post in page_obj.object_list %}
            <div class="card mb-4" onclick="location.href='{{post.get_absolute_url}}';" style="cursor: pointer;">
                <div class="card-body">
                  <h5 class="card-title text-info">{{post.title}}</h5>
                  <p class="card-text">{{post.description|truncatewords:30}}</p>
                </div>
              </div>
            {% endfor %}

            </div>
            
            {% endblock %}

            <div class="col-lg-3  d-none  {% if request.user.is_authenticated %}d-md-block{% endif %} ">
                <div class="card text-bg-secondary mb-3" style="max-width: 18rem;">
                    <div class="card-header">
                        <h2>My Blogs</h2>
                        <p class="fst-italic">Your last 3 posts</p>
                        
                    </div>
                    

                </div>
                {% for myblog in my_blogs  %}

                <div class="card text-bg-light mb-2" style="max-width: 18rem; cursor: pointer;" 
                onclick="{% if myblog.status == 'Publish' %}location.href='{{myblog.get_absolute_url}}';{% else %}location.href='{% url 'pages:post_update' myblog.pk myblog.slug %}';{% endif %}">

                    <div class="card-body">
                      <h6 class="card-title text-info ">{{myblog.title|truncatechars:20}}</h6>
                      <p class="card-text">{{myblog.description|truncatewords:10}}</p>

                      <p class=""><span class="fst-italic">Published {{myblog.updated_at}}</span></p>

                      <div class="d-flex w-50 justify-content-between text-end">
                         <span class="text-secondary">{{myblog.status}}</span>
                        <a href="{% url 'pages:post_update' myblog.pk myblog.slug %}"><i class="fas fa-edit text-primary"></i></a>
                        <a href="{% url 'pages:post_remove' myblog.pk myblog.slug %}"><i class="fas fa-trash text-danger"></i></a>


                       </div>

                    </div>
                </div>
                {% endfor %}


                  

            </div>

        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
              </li>
              {% endif %}
              {% for i in page_obj.paginator.page_range  %}
              {% if page_obj.number == i %}
              <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
               {% else %}
               <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>

              {% endif %}
              {% endfor %}

              {% if  page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
              </li>
              {% endif %}
            </ul>
          </nav>
          
 
    </main>

    {% comment %} #Footer {% endcomment %}



    {% comment %} #Bootstrap Javascript CDNs {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/fontawesome.min.js" integrity="sha512-j3gF1rYV2kvAKJ0Jo5CdgLgSYS7QYmBVVUjduXdoeBkc4NFV4aSRTi+Rodkiy9ht7ZYEwF+s09S43Z1Y+ujUkA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block script %}{% endblock script %}
  </body>
</html>

templates/edit_article.html
{% extends "base.html" %}

{% block content %} 


<!--Edit Article--> 
<div class="col-lg-9 py-3">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h1>{% if request.path == '/posts/create/' %}New Article {% else %}Edit Article{% endif %}</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}                    
                <button class="btn btn-outline-success" type="submit">Submit</button>
            </form>

        </div>
    </div>

</div>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'pages:home' %}">My Blog</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'pages:post_create' %}"
          >Publish Article</a
      

        </li>
        <li class="nav-item">
          {% if not request.user.is_authenticated %}
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'login' %}"
            >Log In</a
          >
          {% else %}
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'pages:logout' %}"
            >Log Out</a
          >
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/post_detail.html
{% extends "base.html" %} {% block title %}

<title>{{post.title}}</title>
{% endblock title %} {% block content %}

<div class="col-lg-9">
  <div id="postlist">
    <div class="panel">
      <div class="panel-heading">
        <div class="text-center">
          <div class="row">
            <div class="col-sm-12 text-start">
              <h3 class="text-info">{{post.title}}</h3>
              <p class="">
                <span class="fst-italic">Published {{post.updated_at}}</span> by
                <span class="badge rounded-pill text-bg-secondary"
                  >{{post.author.username}}</span
                >
              </p>
            </div>
            <hr />
          </div>
        </div>
      </div>

      <div class="panel-body lh-lg fw-light">{{post.description}}</div>
      <p class="p-2 text-info">Share with:</p>
      <div
        class="share-button d-flex mb-4 justify-content-between"
        style="max-width: 160px"
      >
        <a class="facebook" target="_blank"
          ><i class="fab fa-facebook fa-2x"></i
        ></a>
        <a class="twitter text-info" target="_blank"
          ><i class="fab fa-twitter fa-2x"></i
        ></a>
        <a class="linkedin" target="_blank"
          ><i class="fab fa-linkedin fa-2x"></i
        ></a>
        <a
          href="mailto:?subject=Checkout my new article on site&amp;body={{ request.build_absolute_uri }}"
          title="Share by Email"
        >
          <i class="fa-solid fa-envelope fa-2x"></i>
        </a>
      </div>

      <div>
        {% if user.is_authenticated %}
        <form
          action="{% url 'pages:post_like' post.id post.slug %}"
          method="POST"
        >
          {% csrf_token %} {% if post_is_liked %}
          <button
            type="submit"
            name="blogpost_id"
            value="{{post.id}}"
            class="btn btn-info"
          >
            <i class="fas fa-thumbs-down"></i>
          </button>

          {% else %}
          <button
            type="submit"
            name="blogpost_id"
            value="{{post.id}}"
            class="btn btn-info"
          >
            <i class="fas fa-thumbs-up"></i>
          </button>
          {% endif %}
        </form>
        {% else %}
        <a
          class="btn btn-outline-info"
          href="{% url 'login' %}?next={{request.path}}"
          >Log in to like this article!</a
        ><br />
        {% endif %}
        <strong class="text-secondary"
          >{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong
        >
      </div>

      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em">
          {{ comment_form.as_p }} {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>

      <div class="p-4">
        <h5>{{comments|length}} comment{{comments|pluralize}}</h5>
        {% for comment in comments %}
        <div class="card w-100 w-md-50 mb-2">
          <div class="card-body">
            <h6 class="card-title" style="font-size: 15px">
              commented by {{comment.name}}, {{comment.created_at}}
            </h6>
            <p class="card-text">{{comment.content|linebreaks}}</p>

            {% comment %} nested comment {% endcomment %}
            <div class="d-flex flex-row-reverse py-3">
              <p class="card-text">
                {{comment.comment_nestedcomment.all|length}} 
                {% if comment.comment_nestedcomment.all|length > 1 %}Replies {% else %}Reply{% endif %}
              </p>
            </div>

            {% for nested_comment in  comment.comment_nestedcomment.all|slice:"10" %}
            <div>
              <figure class="text-end">
                <blockquote class="blockquote">
                  <p style="font-size: 0.75rem">
                    <small
                      >{{nested_comment.name}}.
                      {{nested_comment.created_at|timesince}} ago</small
                    >
                  </p>
                </blockquote>
                <figcaption class="blockquote-footer">
                  <cite title="Source Title">{{nested_comment.content}}</cite>
                </figcaption>
              </figure>
            </div>

            {% endfor %}

            <p class="float-end">
              <a
                class="btn btn-secondary"
                data-bs-toggle="collapse"
                href="#collapseExample"
                role="button"
                aria-expanded="false"
                aria-controls="collapseExample"
              >
                comment
              </a>
            </p>
            <div
              class="collapse"
              id="collapseExample"
              style="margin-top: 3.4rem !important"
            >
              <div class="card card-body">
                <form action="{% url 'pages:nested_comment' %}" method="post">
                  {% csrf_token %} {{nested_comment_form.as_p}}
                  <input
                    type="text"
                    name="post_id"
                    value="{{post.id}}"
                    hidden
                  />
                  <input
                    type="text"
                    name="comment_id"
                    value="{{comment.id}}"
                    hidden
                  />

                  <button type="submit" class="btn btn-primary btn-sm">
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block script %}
<script>
  const link = encodeURI(window.location.href);
  const msg = encodeURIComponent("{{post.desciption}}");
  const title = encodeURIComponent("{{post.title}}");

  const facebook = document.querySelector(".facebook");
  facebook.href = `https://www.facebook.com/share.php?u=${link}`;

  const twitter = document.querySelector(".twitter");
  twitter.href = `https://twitter.com/intent/tweet?url=${link}&text="{{post.title}}"`;

  const linkedIn = document.querySelector(".linkedin");
  linkedIn.href = `https://www.linkedin.com/sharing/share-offsite/?url=${link}`;
</script>
{% endblock script %}